import { type NextPage } from "next";
import Head from "next/head";
import NextImage from "next/image";
import HeroImg from "../../public/hero.webp";
import { Button } from "@ui/Button";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="grid grid-cols-1 grid-rows-[45vh_45vh]">
          <div className="relative">
            <NextImage src={HeroImg} fill style={{ objectFit: "cover" }} alt="" />
          </div>
          <div>
            <h1 className="w-[70%] text-center mx-auto my-6">Meet your new favorite pantry staple!</h1>
            <div className="font-light text-opacity-75 w-[80%] mx-auto text-center">Cook restaurant-quality Asian dishes in under 30 minutes with our meal starters.</div>
            <div className="mx-auto w-44 my-6"><Button href="/meal-starters">Shop Now</Button></div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
