import { type NextPage } from "next";
import Head from "next/head";
import NextImage from "next/image";
import HeroImg from "../../public/hero.webp";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="grid grid-cols-1 grid-rows-[50vh_50vh]">
          <div className="relative">
            <NextImage src={HeroImg} fill style={{ objectFit: "cover" }} alt="" />
          </div>
          <div>
            <h2 className="text-lg">Meet your new favorite pantry staple!</h2>
            <button></button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
